### PR TITLE
Include additional parameters

### PR DESCRIPTION
**Pull request by hexhowells**

### CODE REVIEW

**Comment by pcm32** [comment]
Ok, not sure why the tests are not being shown here. But I see them on your branch.

**Comment by pcm32** [comment]
Could you please add [here](https://github.com/hexhowells/scmap-cli/blob/develop/scmap-cli-post-install-tests.bats) in the adequate places modifications that would use your new parameters? It could be repetitions with parameters alterations, since tests are fairly quickly (and then we keep testing the version that is not using the alterations, which is good).

**Comment by pcm32** [comment]
Could you please make sure now that the tests pass: https://github.com/hexhowells/scmap-cli/actions/runs/6248061414/job/16961891590 ? Thanks!

**Review by pcm32 — APPROVED** [review]
Great contribution @hexhowells, thanks! LGTM!

**Comment by pcm32** [comment]
Do you get the squash and merge button above @hexhowells ? if you do, please merge like that (squashed merge), otherwise let me know and I can merge it.

**Comment by hexhowells** [comment]
Thanks! And I can't see any buttons for merging.

**Comment by hexhowells** [comment]
@pcm32 do you know what next steps are needed to get these changes integrated into the Galaxy tools? From what I can tell the added parameters are not currently present on any of the the Galaxy UI servers. Thanks!

**Comment by pcm32** [comment]
Sorry, only saw this yesterday. I have now made a new release in Github, it should be picked up by the auto bump in bioconda here https://github.com/bioconda/bioconda-recipes/pulls - when that happens and it is merged, we can make a PR at https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/tree/develop/tools/tertiary-analysis/scmap with the parameter change. Then when that is merged it will be available for update on all the galaxy instances.

**Comment by hexhowells** [comment]
I've made a pull request with the parameter change here: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/310. I'm not familiar with the process of updating tools so not sure if there was anything I missed and needed to change.

**Comment by pcm32** [comment]
I have added some comments on your PR there.

**Pull request merged**
